package com.hqkj.example.entity;

public class ADictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary.modelid
     *
     * @mbggenerated
     */
    private Integer modelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary.modeldesc
     *
     * @mbggenerated
     */
    private String modeldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary.functionid
     *
     * @mbggenerated
     */
    private String functionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary.functiondesc
     *
     * @mbggenerated
     */
    private String functiondesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary.id
     *
     * @return the value of a_dictionary.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary.id
     *
     * @param id the value for a_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary.modelid
     *
     * @return the value of a_dictionary.modelid
     *
     * @mbggenerated
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary.modelid
     *
     * @param modelid the value for a_dictionary.modelid
     *
     * @mbggenerated
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary.modeldesc
     *
     * @return the value of a_dictionary.modeldesc
     *
     * @mbggenerated
     */
    public String getModeldesc() {
        return modeldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary.modeldesc
     *
     * @param modeldesc the value for a_dictionary.modeldesc
     *
     * @mbggenerated
     */
    public void setModeldesc(String modeldesc) {
        this.modeldesc = modeldesc == null ? null : modeldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary.functionid
     *
     * @return the value of a_dictionary.functionid
     *
     * @mbggenerated
     */
    public String getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary.functionid
     *
     * @param functionid the value for a_dictionary.functionid
     *
     * @mbggenerated
     */
    public void setFunctionid(String functionid) {
        this.functionid = functionid == null ? null : functionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary.functiondesc
     *
     * @return the value of a_dictionary.functiondesc
     *
     * @mbggenerated
     */
    public String getFunctiondesc() {
        return functiondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary.functiondesc
     *
     * @param functiondesc the value for a_dictionary.functiondesc
     *
     * @mbggenerated
     */
    public void setFunctiondesc(String functiondesc) {
        this.functiondesc = functiondesc == null ? null : functiondesc.trim();
    }
}