package com.hqkj.example.entity;

import java.util.Date;

public class Deviceinput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.deviceid
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.deviceid_type
     *
     * @mbggenerated
     */
    private Integer deviceidType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.is_video
     *
     * @mbggenerated
     */
    private Byte isVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.input_time
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deviceinput.use_time
     *
     * @mbggenerated
     */
    private Date useTime;



    private Integer operationStatus;


    public Integer getOperationStatus() {
        return operationStatus;
    }

    public void setOperationStatus(Integer operationStatus) {
        this.operationStatus = operationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.id
     *
     * @return the value of deviceinput.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.id
     *
     * @param id the value for deviceinput.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.deviceid
     *
     * @return the value of deviceinput.deviceid
     *
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.deviceid
     *
     * @param deviceid the value for deviceinput.deviceid
     *
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.deviceid_type
     *
     * @return the value of deviceinput.deviceid_type
     *
     * @mbggenerated
     */
    public Integer getDeviceidType() {
        return deviceidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.deviceid_type
     *
     * @param deviceidType the value for deviceinput.deviceid_type
     *
     * @mbggenerated
     */
    public void setDeviceidType(Integer deviceidType) {
        this.deviceidType = deviceidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.is_video
     *
     * @return the value of deviceinput.is_video
     *
     * @mbggenerated
     */
    public Byte getIsVideo() {
        return isVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.is_video
     *
     * @param isVideo the value for deviceinput.is_video
     *
     * @mbggenerated
     */
    public void setIsVideo(Byte isVideo) {
        this.isVideo = isVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.user_id
     *
     * @return the value of deviceinput.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.user_id
     *
     * @param userId the value for deviceinput.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.remark
     *
     * @return the value of deviceinput.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.remark
     *
     * @param remark the value for deviceinput.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.status
     *
     * @return the value of deviceinput.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.status
     *
     * @param status the value for deviceinput.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.input_time
     *
     * @return the value of deviceinput.input_time
     *
     * @mbggenerated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.input_time
     *
     * @param inputTime the value for deviceinput.input_time
     *
     * @mbggenerated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deviceinput.use_time
     *
     * @return the value of deviceinput.use_time
     *
     * @mbggenerated
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deviceinput.use_time
     *
     * @param useTime the value for deviceinput.use_time
     *
     * @mbggenerated
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }
}