package com.hqkj.example.entity;

public class Devicetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicetype.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicetype.device_type
     *
     * @mbggenerated
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicetype.manufacturer_no
     *
     * @mbggenerated
     */
    private String manufacturerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicetype.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicetype.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicetype.id
     *
     * @return the value of devicetype.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicetype.id
     *
     * @param id the value for devicetype.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicetype.device_type
     *
     * @return the value of devicetype.device_type
     *
     * @mbggenerated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicetype.device_type
     *
     * @param deviceType the value for devicetype.device_type
     *
     * @mbggenerated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicetype.manufacturer_no
     *
     * @return the value of devicetype.manufacturer_no
     *
     * @mbggenerated
     */
    public String getManufacturerNo() {
        return manufacturerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicetype.manufacturer_no
     *
     * @param manufacturerNo the value for devicetype.manufacturer_no
     *
     * @mbggenerated
     */
    public void setManufacturerNo(String manufacturerNo) {
        this.manufacturerNo = manufacturerNo == null ? null : manufacturerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicetype.manufacturer
     *
     * @return the value of devicetype.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicetype.manufacturer
     *
     * @param manufacturer the value for devicetype.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicetype.remark
     *
     * @return the value of devicetype.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicetype.remark
     *
     * @param remark the value for devicetype.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}