package com.hqkj.example.entity;

public class Driver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver
     *
     * @mbggenerated
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.qualification
     *
     * @mbggenerated
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.license_num
     *
     * @mbggenerated
     */
    private String licenseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.driver_phone
     *
     * @mbggenerated
     */
    private String driverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.license_photo
     *
     * @mbggenerated
     */
    private String licensePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.iccard
     *
     * @mbggenerated
     */
    private String iccard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.id
     *
     * @return the value of driver.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.id
     *
     * @param id the value for driver.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver
     *
     * @return the value of driver.driver
     *
     * @mbggenerated
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver
     *
     * @param driver the value for driver.driver
     *
     * @mbggenerated
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.qualification
     *
     * @return the value of driver.qualification
     *
     * @mbggenerated
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.qualification
     *
     * @param qualification the value for driver.qualification
     *
     * @mbggenerated
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.license_num
     *
     * @return the value of driver.license_num
     *
     * @mbggenerated
     */
    public String getLicenseNum() {
        return licenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.license_num
     *
     * @param licenseNum the value for driver.license_num
     *
     * @mbggenerated
     */
    public void setLicenseNum(String licenseNum) {
        this.licenseNum = licenseNum == null ? null : licenseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.driver_phone
     *
     * @return the value of driver.driver_phone
     *
     * @mbggenerated
     */
    public String getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.driver_phone
     *
     * @param driverPhone the value for driver.driver_phone
     *
     * @mbggenerated
     */
    public void setDriverPhone(String driverPhone) {
        this.driverPhone = driverPhone == null ? null : driverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.license_photo
     *
     * @return the value of driver.license_photo
     *
     * @mbggenerated
     */
    public String getLicensePhoto() {
        return licensePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.license_photo
     *
     * @param licensePhoto the value for driver.license_photo
     *
     * @mbggenerated
     */
    public void setLicensePhoto(String licensePhoto) {
        this.licensePhoto = licensePhoto == null ? null : licensePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.iccard
     *
     * @return the value of driver.iccard
     *
     * @mbggenerated
     */
    public String getIccard() {
        return iccard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.iccard
     *
     * @param iccard the value for driver.iccard
     *
     * @mbggenerated
     */
    public void setIccard(String iccard) {
        this.iccard = iccard == null ? null : iccard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver.status
     *
     * @return the value of driver.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver.status
     *
     * @param status the value for driver.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}