package com.hqkj.example.entity;

public class Func {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_id
     *
     * @mbggenerated
     */
    private Integer funcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_name
     *
     * @mbggenerated
     */
    private String funcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_img
     *
     * @mbggenerated
     */
    private String funcImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.is_leaf
     *
     * @mbggenerated
     */
    private Byte isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_path
     *
     * @mbggenerated
     */
    private String funcPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.func_type
     *
     * @mbggenerated
     */
    private Byte funcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.is_short
     *
     * @mbggenerated
     */
    private Byte isShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.short_img
     *
     * @mbggenerated
     */
    private String shortImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func.short_sort_order
     *
     * @mbggenerated
     */
    private Integer shortSortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_id
     *
     * @return the value of func.func_id
     *
     * @mbggenerated
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_id
     *
     * @param funcId the value for func.func_id
     *
     * @mbggenerated
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_name
     *
     * @return the value of func.func_name
     *
     * @mbggenerated
     */
    public String getFuncName() {
        return funcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_name
     *
     * @param funcName the value for func.func_name
     *
     * @mbggenerated
     */
    public void setFuncName(String funcName) {
        this.funcName = funcName == null ? null : funcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_img
     *
     * @return the value of func.func_img
     *
     * @mbggenerated
     */
    public String getFuncImg() {
        return funcImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_img
     *
     * @param funcImg the value for func.func_img
     *
     * @mbggenerated
     */
    public void setFuncImg(String funcImg) {
        this.funcImg = funcImg == null ? null : funcImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.level
     *
     * @return the value of func.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.level
     *
     * @param level the value for func.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.parent_id
     *
     * @return the value of func.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.parent_id
     *
     * @param parentId the value for func.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.is_leaf
     *
     * @return the value of func.is_leaf
     *
     * @mbggenerated
     */
    public Byte getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.is_leaf
     *
     * @param isLeaf the value for func.is_leaf
     *
     * @mbggenerated
     */
    public void setIsLeaf(Byte isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_path
     *
     * @return the value of func.func_path
     *
     * @mbggenerated
     */
    public String getFuncPath() {
        return funcPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_path
     *
     * @param funcPath the value for func.func_path
     *
     * @mbggenerated
     */
    public void setFuncPath(String funcPath) {
        this.funcPath = funcPath == null ? null : funcPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.sort_order
     *
     * @return the value of func.sort_order
     *
     * @mbggenerated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.sort_order
     *
     * @param sortOrder the value for func.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.func_type
     *
     * @return the value of func.func_type
     *
     * @mbggenerated
     */
    public Byte getFuncType() {
        return funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.func_type
     *
     * @param funcType the value for func.func_type
     *
     * @mbggenerated
     */
    public void setFuncType(Byte funcType) {
        this.funcType = funcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.status
     *
     * @return the value of func.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.status
     *
     * @param status the value for func.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.is_short
     *
     * @return the value of func.is_short
     *
     * @mbggenerated
     */
    public Byte getIsShort() {
        return isShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.is_short
     *
     * @param isShort the value for func.is_short
     *
     * @mbggenerated
     */
    public void setIsShort(Byte isShort) {
        this.isShort = isShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.short_img
     *
     * @return the value of func.short_img
     *
     * @mbggenerated
     */
    public String getShortImg() {
        return shortImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.short_img
     *
     * @param shortImg the value for func.short_img
     *
     * @mbggenerated
     */
    public void setShortImg(String shortImg) {
        this.shortImg = shortImg == null ? null : shortImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func.short_sort_order
     *
     * @return the value of func.short_sort_order
     *
     * @mbggenerated
     */
    public Integer getShortSortOrder() {
        return shortSortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func.short_sort_order
     *
     * @param shortSortOrder the value for func.short_sort_order
     *
     * @mbggenerated
     */
    public void setShortSortOrder(Integer shortSortOrder) {
        this.shortSortOrder = shortSortOrder;
    }
}