package com.hqkj.example.entity;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.region_id
     *
     * @mbggenerated
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.region_name
     *
     * @mbggenerated
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.region_type
     *
     * @mbggenerated
     */
    private Byte regionType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.region_id
     *
     * @return the value of region.region_id
     *
     * @mbggenerated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.region_id
     *
     * @param regionId the value for region.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.region_name
     *
     * @return the value of region.region_name
     *
     * @mbggenerated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.region_name
     *
     * @param regionName the value for region.region_name
     *
     * @mbggenerated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.parent_id
     *
     * @return the value of region.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.parent_id
     *
     * @param parentId the value for region.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.region_type
     *
     * @return the value of region.region_type
     *
     * @mbggenerated
     */
    public Byte getRegionType() {
        return regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.region_type
     *
     * @param regionType the value for region.region_type
     *
     * @mbggenerated
     */
    public void setRegionType(Byte regionType) {
        this.regionType = regionType;
    }
}