package com.hqkj.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Sim {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.sim_no
     *
     * @mbggenerated
     */
    private String simNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.sim_type
     *
     * @mbggenerated
     */
    private Byte simType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.lease
     *
     * @mbggenerated
     */
    private Byte lease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.rent
     *
     * @mbggenerated
     */
    private BigDecimal rent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.packagevoice
     *
     * @mbggenerated
     */
    private Integer packagevoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.packageflow
     *
     * @mbggenerated
     */
    private Integer packageflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.carrier
     *
     * @mbggenerated
     */
    private Byte carrier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.ICCID
     *
     * @mbggenerated
     */
    private String iccid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.input_time
     *
     * @mbggenerated
     */
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.use_time
     *
     * @mbggenerated
     */
    private Date useTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.id
     *
     * @return the value of sim.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.id
     *
     * @param id the value for sim.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.sim_no
     *
     * @return the value of sim.sim_no
     *
     * @mbggenerated
     */
    public String getSimNo() {
        return simNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.sim_no
     *
     * @param simNo the value for sim.sim_no
     *
     * @mbggenerated
     */
    public void setSimNo(String simNo) {
        this.simNo = simNo == null ? null : simNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.sim_type
     *
     * @return the value of sim.sim_type
     *
     * @mbggenerated
     */
    public Byte getSimType() {
        return simType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.sim_type
     *
     * @param simType the value for sim.sim_type
     *
     * @mbggenerated
     */
    public void setSimType(Byte simType) {
        this.simType = simType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.lease
     *
     * @return the value of sim.lease
     *
     * @mbggenerated
     */
    public Byte getLease() {
        return lease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.lease
     *
     * @param lease the value for sim.lease
     *
     * @mbggenerated
     */
    public void setLease(Byte lease) {
        this.lease = lease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.rent
     *
     * @return the value of sim.rent
     *
     * @mbggenerated
     */
    public BigDecimal getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.rent
     *
     * @param rent the value for sim.rent
     *
     * @mbggenerated
     */
    public void setRent(BigDecimal rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.packagevoice
     *
     * @return the value of sim.packagevoice
     *
     * @mbggenerated
     */
    public Integer getPackagevoice() {
        return packagevoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.packagevoice
     *
     * @param packagevoice the value for sim.packagevoice
     *
     * @mbggenerated
     */
    public void setPackagevoice(Integer packagevoice) {
        this.packagevoice = packagevoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.packageflow
     *
     * @return the value of sim.packageflow
     *
     * @mbggenerated
     */
    public Integer getPackageflow() {
        return packageflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.packageflow
     *
     * @param packageflow the value for sim.packageflow
     *
     * @mbggenerated
     */
    public void setPackageflow(Integer packageflow) {
        this.packageflow = packageflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.carrier
     *
     * @return the value of sim.carrier
     *
     * @mbggenerated
     */
    public Byte getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.carrier
     *
     * @param carrier the value for sim.carrier
     *
     * @mbggenerated
     */
    public void setCarrier(Byte carrier) {
        this.carrier = carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.user_id
     *
     * @return the value of sim.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.user_id
     *
     * @param userId the value for sim.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.ICCID
     *
     * @return the value of sim.ICCID
     *
     * @mbggenerated
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.ICCID
     *
     * @param iccid the value for sim.ICCID
     *
     * @mbggenerated
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.status
     *
     * @return the value of sim.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.status
     *
     * @param status the value for sim.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.input_time
     *
     * @return the value of sim.input_time
     *
     * @mbggenerated
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.input_time
     *
     * @param inputTime the value for sim.input_time
     *
     * @mbggenerated
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.use_time
     *
     * @return the value of sim.use_time
     *
     * @mbggenerated
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.use_time
     *
     * @param useTime the value for sim.use_time
     *
     * @mbggenerated
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim.remark
     *
     * @return the value of sim.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim.remark
     *
     * @param remark the value for sim.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}