package com.hqkj.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Vehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_id
     *
     * @mbggenerated
     */
    private Integer vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.licence_no
     *
     * @mbggenerated
     */
    private String licenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.licence_color
     *
     * @mbggenerated
     */
    private Byte licenceColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.manage_licence
     *
     * @mbggenerated
     */
    private String manageLicence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vin
     *
     * @mbggenerated
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.engine_no
     *
     * @mbggenerated
     */
    private String engineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.seat
     *
     * @mbggenerated
     */
    private Integer seat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vcat
     *
     * @mbggenerated
     */
    private String vcat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vehicle_type_id
     *
     * @mbggenerated
     */
    private Integer vehicleTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vtype
     *
     * @mbggenerated
     */
    private Integer vtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.full_weight
     *
     * @mbggenerated
     */
    private BigDecimal fullWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.approved_quality
     *
     * @mbggenerated
     */
    private BigDecimal approvedQuality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.traction_quality
     *
     * @mbggenerated
     */
    private BigDecimal tractionQuality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.outline_long
     *
     * @mbggenerated
     */
    private BigDecimal outlineLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.outline_wide
     *
     * @mbggenerated
     */
    private BigDecimal outlineWide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.outline_high
     *
     * @mbggenerated
     */
    private BigDecimal outlineHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.axes_num
     *
     * @mbggenerated
     */
    private BigDecimal axesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.install_date
     *
     * @mbggenerated
     */
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.service_expires
     *
     * @mbggenerated
     */
    private Date serviceExpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.deviceid
     *
     * @mbggenerated
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.sim_no
     *
     * @mbggenerated
     */
    private String simNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.installer
     *
     * @mbggenerated
     */
    private String installer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.install_place
     *
     * @mbggenerated
     */
    private String installPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.video_service
     *
     * @mbggenerated
     */
    private String videoService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.pass_num
     *
     * @mbggenerated
     */
    private Long passNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.carload_photo_path
     *
     * @mbggenerated
     */
    private String carloadPhotoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.driving_license_photo
     *
     * @mbggenerated
     */
    private String drivingLicensePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.registration1_photo
     *
     * @mbggenerated
     */
    private String registration1Photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.registration2_photo
     *
     * @mbggenerated
     */
    private String registration2Photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.manage_licence_photo
     *
     * @mbggenerated
     */
    private String manageLicencePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.install_place_photo
     *
     * @mbggenerated
     */
    private String installPlacePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.connection_photo
     *
     * @mbggenerated
     */
    private String connectionPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.owner_name
     *
     * @mbggenerated
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.contacts
     *
     * @mbggenerated
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.operator
     *
     * @mbggenerated
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_id
     *
     * @return the value of vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_id
     *
     * @param vehicleId the value for vehicle.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.licence_no
     *
     * @return the value of vehicle.licence_no
     *
     * @mbggenerated
     */
    public String getLicenceNo() {
        return licenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.licence_no
     *
     * @param licenceNo the value for vehicle.licence_no
     *
     * @mbggenerated
     */
    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo == null ? null : licenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.licence_color
     *
     * @return the value of vehicle.licence_color
     *
     * @mbggenerated
     */
    public Byte getLicenceColor() {
        return licenceColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.licence_color
     *
     * @param licenceColor the value for vehicle.licence_color
     *
     * @mbggenerated
     */
    public void setLicenceColor(Byte licenceColor) {
        this.licenceColor = licenceColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.manage_licence
     *
     * @return the value of vehicle.manage_licence
     *
     * @mbggenerated
     */
    public String getManageLicence() {
        return manageLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.manage_licence
     *
     * @param manageLicence the value for vehicle.manage_licence
     *
     * @mbggenerated
     */
    public void setManageLicence(String manageLicence) {
        this.manageLicence = manageLicence == null ? null : manageLicence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.group_id
     *
     * @return the value of vehicle.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.group_id
     *
     * @param groupId the value for vehicle.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.area
     *
     * @return the value of vehicle.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.area
     *
     * @param area the value for vehicle.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vin
     *
     * @return the value of vehicle.vin
     *
     * @mbggenerated
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vin
     *
     * @param vin the value for vehicle.vin
     *
     * @mbggenerated
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.engine_no
     *
     * @return the value of vehicle.engine_no
     *
     * @mbggenerated
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.engine_no
     *
     * @param engineNo the value for vehicle.engine_no
     *
     * @mbggenerated
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.seat
     *
     * @return the value of vehicle.seat
     *
     * @mbggenerated
     */
    public Integer getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.seat
     *
     * @param seat the value for vehicle.seat
     *
     * @mbggenerated
     */
    public void setSeat(Integer seat) {
        this.seat = seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vcat
     *
     * @return the value of vehicle.vcat
     *
     * @mbggenerated
     */
    public String getVcat() {
        return vcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vcat
     *
     * @param vcat the value for vehicle.vcat
     *
     * @mbggenerated
     */
    public void setVcat(String vcat) {
        this.vcat = vcat == null ? null : vcat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vehicle_type_id
     *
     * @return the value of vehicle.vehicle_type_id
     *
     * @mbggenerated
     */
    public Integer getVehicleTypeId() {
        return vehicleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vehicle_type_id
     *
     * @param vehicleTypeId the value for vehicle.vehicle_type_id
     *
     * @mbggenerated
     */
    public void setVehicleTypeId(Integer vehicleTypeId) {
        this.vehicleTypeId = vehicleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vtype
     *
     * @return the value of vehicle.vtype
     *
     * @mbggenerated
     */
    public Integer getVtype() {
        return vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vtype
     *
     * @param vtype the value for vehicle.vtype
     *
     * @mbggenerated
     */
    public void setVtype(Integer vtype) {
        this.vtype = vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.full_weight
     *
     * @return the value of vehicle.full_weight
     *
     * @mbggenerated
     */
    public BigDecimal getFullWeight() {
        return fullWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.full_weight
     *
     * @param fullWeight the value for vehicle.full_weight
     *
     * @mbggenerated
     */
    public void setFullWeight(BigDecimal fullWeight) {
        this.fullWeight = fullWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.approved_quality
     *
     * @return the value of vehicle.approved_quality
     *
     * @mbggenerated
     */
    public BigDecimal getApprovedQuality() {
        return approvedQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.approved_quality
     *
     * @param approvedQuality the value for vehicle.approved_quality
     *
     * @mbggenerated
     */
    public void setApprovedQuality(BigDecimal approvedQuality) {
        this.approvedQuality = approvedQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.traction_quality
     *
     * @return the value of vehicle.traction_quality
     *
     * @mbggenerated
     */
    public BigDecimal getTractionQuality() {
        return tractionQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.traction_quality
     *
     * @param tractionQuality the value for vehicle.traction_quality
     *
     * @mbggenerated
     */
    public void setTractionQuality(BigDecimal tractionQuality) {
        this.tractionQuality = tractionQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.outline_long
     *
     * @return the value of vehicle.outline_long
     *
     * @mbggenerated
     */
    public BigDecimal getOutlineLong() {
        return outlineLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.outline_long
     *
     * @param outlineLong the value for vehicle.outline_long
     *
     * @mbggenerated
     */
    public void setOutlineLong(BigDecimal outlineLong) {
        this.outlineLong = outlineLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.outline_wide
     *
     * @return the value of vehicle.outline_wide
     *
     * @mbggenerated
     */
    public BigDecimal getOutlineWide() {
        return outlineWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.outline_wide
     *
     * @param outlineWide the value for vehicle.outline_wide
     *
     * @mbggenerated
     */
    public void setOutlineWide(BigDecimal outlineWide) {
        this.outlineWide = outlineWide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.outline_high
     *
     * @return the value of vehicle.outline_high
     *
     * @mbggenerated
     */
    public BigDecimal getOutlineHigh() {
        return outlineHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.outline_high
     *
     * @param outlineHigh the value for vehicle.outline_high
     *
     * @mbggenerated
     */
    public void setOutlineHigh(BigDecimal outlineHigh) {
        this.outlineHigh = outlineHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.axes_num
     *
     * @return the value of vehicle.axes_num
     *
     * @mbggenerated
     */
    public BigDecimal getAxesNum() {
        return axesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.axes_num
     *
     * @param axesNum the value for vehicle.axes_num
     *
     * @mbggenerated
     */
    public void setAxesNum(BigDecimal axesNum) {
        this.axesNum = axesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.install_date
     *
     * @return the value of vehicle.install_date
     *
     * @mbggenerated
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.install_date
     *
     * @param installDate the value for vehicle.install_date
     *
     * @mbggenerated
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.service_expires
     *
     * @return the value of vehicle.service_expires
     *
     * @mbggenerated
     */
    public Date getServiceExpires() {
        return serviceExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.service_expires
     *
     * @param serviceExpires the value for vehicle.service_expires
     *
     * @mbggenerated
     */
    public void setServiceExpires(Date serviceExpires) {
        this.serviceExpires = serviceExpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.deviceid
     *
     * @return the value of vehicle.deviceid
     *
     * @mbggenerated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.deviceid
     *
     * @param deviceid the value for vehicle.deviceid
     *
     * @mbggenerated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.sim_no
     *
     * @return the value of vehicle.sim_no
     *
     * @mbggenerated
     */
    public String getSimNo() {
        return simNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.sim_no
     *
     * @param simNo the value for vehicle.sim_no
     *
     * @mbggenerated
     */
    public void setSimNo(String simNo) {
        this.simNo = simNo == null ? null : simNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.installer
     *
     * @return the value of vehicle.installer
     *
     * @mbggenerated
     */
    public String getInstaller() {
        return installer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.installer
     *
     * @param installer the value for vehicle.installer
     *
     * @mbggenerated
     */
    public void setInstaller(String installer) {
        this.installer = installer == null ? null : installer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.install_place
     *
     * @return the value of vehicle.install_place
     *
     * @mbggenerated
     */
    public String getInstallPlace() {
        return installPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.install_place
     *
     * @param installPlace the value for vehicle.install_place
     *
     * @mbggenerated
     */
    public void setInstallPlace(String installPlace) {
        this.installPlace = installPlace == null ? null : installPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.video_service
     *
     * @return the value of vehicle.video_service
     *
     * @mbggenerated
     */
    public String getVideoService() {
        return videoService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.video_service
     *
     * @param videoService the value for vehicle.video_service
     *
     * @mbggenerated
     */
    public void setVideoService(String videoService) {
        this.videoService = videoService == null ? null : videoService.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.pass_num
     *
     * @return the value of vehicle.pass_num
     *
     * @mbggenerated
     */
    public Long getPassNum() {
        return passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.pass_num
     *
     * @param passNum the value for vehicle.pass_num
     *
     * @mbggenerated
     */
    public void setPassNum(Long passNum) {
        this.passNum = passNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.carload_photo_path
     *
     * @return the value of vehicle.carload_photo_path
     *
     * @mbggenerated
     */
    public String getCarloadPhotoPath() {
        return carloadPhotoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.carload_photo_path
     *
     * @param carloadPhotoPath the value for vehicle.carload_photo_path
     *
     * @mbggenerated
     */
    public void setCarloadPhotoPath(String carloadPhotoPath) {
        this.carloadPhotoPath = carloadPhotoPath == null ? null : carloadPhotoPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.driving_license_photo
     *
     * @return the value of vehicle.driving_license_photo
     *
     * @mbggenerated
     */
    public String getDrivingLicensePhoto() {
        return drivingLicensePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.driving_license_photo
     *
     * @param drivingLicensePhoto the value for vehicle.driving_license_photo
     *
     * @mbggenerated
     */
    public void setDrivingLicensePhoto(String drivingLicensePhoto) {
        this.drivingLicensePhoto = drivingLicensePhoto == null ? null : drivingLicensePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.registration1_photo
     *
     * @return the value of vehicle.registration1_photo
     *
     * @mbggenerated
     */
    public String getRegistration1Photo() {
        return registration1Photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.registration1_photo
     *
     * @param registration1Photo the value for vehicle.registration1_photo
     *
     * @mbggenerated
     */
    public void setRegistration1Photo(String registration1Photo) {
        this.registration1Photo = registration1Photo == null ? null : registration1Photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.registration2_photo
     *
     * @return the value of vehicle.registration2_photo
     *
     * @mbggenerated
     */
    public String getRegistration2Photo() {
        return registration2Photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.registration2_photo
     *
     * @param registration2Photo the value for vehicle.registration2_photo
     *
     * @mbggenerated
     */
    public void setRegistration2Photo(String registration2Photo) {
        this.registration2Photo = registration2Photo == null ? null : registration2Photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.manage_licence_photo
     *
     * @return the value of vehicle.manage_licence_photo
     *
     * @mbggenerated
     */
    public String getManageLicencePhoto() {
        return manageLicencePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.manage_licence_photo
     *
     * @param manageLicencePhoto the value for vehicle.manage_licence_photo
     *
     * @mbggenerated
     */
    public void setManageLicencePhoto(String manageLicencePhoto) {
        this.manageLicencePhoto = manageLicencePhoto == null ? null : manageLicencePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.install_place_photo
     *
     * @return the value of vehicle.install_place_photo
     *
     * @mbggenerated
     */
    public String getInstallPlacePhoto() {
        return installPlacePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.install_place_photo
     *
     * @param installPlacePhoto the value for vehicle.install_place_photo
     *
     * @mbggenerated
     */
    public void setInstallPlacePhoto(String installPlacePhoto) {
        this.installPlacePhoto = installPlacePhoto == null ? null : installPlacePhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.connection_photo
     *
     * @return the value of vehicle.connection_photo
     *
     * @mbggenerated
     */
    public String getConnectionPhoto() {
        return connectionPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.connection_photo
     *
     * @param connectionPhoto the value for vehicle.connection_photo
     *
     * @mbggenerated
     */
    public void setConnectionPhoto(String connectionPhoto) {
        this.connectionPhoto = connectionPhoto == null ? null : connectionPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.owner_name
     *
     * @return the value of vehicle.owner_name
     *
     * @mbggenerated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.owner_name
     *
     * @param ownerName the value for vehicle.owner_name
     *
     * @mbggenerated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.contacts
     *
     * @return the value of vehicle.contacts
     *
     * @mbggenerated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.contacts
     *
     * @param contacts the value for vehicle.contacts
     *
     * @mbggenerated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.phone
     *
     * @return the value of vehicle.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.phone
     *
     * @param phone the value for vehicle.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.remark
     *
     * @return the value of vehicle.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.remark
     *
     * @param remark the value for vehicle.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.status
     *
     * @return the value of vehicle.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.status
     *
     * @param status the value for vehicle.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.operator
     *
     * @return the value of vehicle.operator
     *
     * @mbggenerated
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.operator
     *
     * @param operator the value for vehicle.operator
     *
     * @mbggenerated
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.operate_time
     *
     * @return the value of vehicle.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.operate_time
     *
     * @param operateTime the value for vehicle.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}