package com.hqkj.example.entity;

public class VehicleBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_brand.vtype
     *
     * @mbggenerated
     */
    private Integer vtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_brand.vtypename
     *
     * @mbggenerated
     */
    private String vtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_brand.vmodel
     *
     * @mbggenerated
     */
    private String vmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_brand.vtdesc
     *
     * @mbggenerated
     */
    private String vtdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_brand.vtype
     *
     * @return the value of vehicle_brand.vtype
     *
     * @mbggenerated
     */
    public Integer getVtype() {
        return vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_brand.vtype
     *
     * @param vtype the value for vehicle_brand.vtype
     *
     * @mbggenerated
     */
    public void setVtype(Integer vtype) {
        this.vtype = vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_brand.vtypename
     *
     * @return the value of vehicle_brand.vtypename
     *
     * @mbggenerated
     */
    public String getVtypename() {
        return vtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_brand.vtypename
     *
     * @param vtypename the value for vehicle_brand.vtypename
     *
     * @mbggenerated
     */
    public void setVtypename(String vtypename) {
        this.vtypename = vtypename == null ? null : vtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_brand.vmodel
     *
     * @return the value of vehicle_brand.vmodel
     *
     * @mbggenerated
     */
    public String getVmodel() {
        return vmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_brand.vmodel
     *
     * @param vmodel the value for vehicle_brand.vmodel
     *
     * @mbggenerated
     */
    public void setVmodel(String vmodel) {
        this.vmodel = vmodel == null ? null : vmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_brand.vtdesc
     *
     * @return the value of vehicle_brand.vtdesc
     *
     * @mbggenerated
     */
    public String getVtdesc() {
        return vtdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_brand.vtdesc
     *
     * @param vtdesc the value for vehicle_brand.vtdesc
     *
     * @mbggenerated
     */
    public void setVtdesc(String vtdesc) {
        this.vtdesc = vtdesc == null ? null : vtdesc.trim();
    }
}