package com.hqkj.example.entity;

public class VehicleDriver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_driver.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_driver.licence_no
     *
     * @mbggenerated
     */
    private String licenceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_driver.licence_color
     *
     * @mbggenerated
     */
    private String licenceColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_driver.driverid
     *
     * @mbggenerated
     */
    private Integer driverid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_driver.id
     *
     * @return the value of vehicle_driver.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_driver.id
     *
     * @param id the value for vehicle_driver.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_driver.licence_no
     *
     * @return the value of vehicle_driver.licence_no
     *
     * @mbggenerated
     */
    public String getLicenceNo() {
        return licenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_driver.licence_no
     *
     * @param licenceNo the value for vehicle_driver.licence_no
     *
     * @mbggenerated
     */
    public void setLicenceNo(String licenceNo) {
        this.licenceNo = licenceNo == null ? null : licenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_driver.licence_color
     *
     * @return the value of vehicle_driver.licence_color
     *
     * @mbggenerated
     */
    public String getLicenceColor() {
        return licenceColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_driver.licence_color
     *
     * @param licenceColor the value for vehicle_driver.licence_color
     *
     * @mbggenerated
     */
    public void setLicenceColor(String licenceColor) {
        this.licenceColor = licenceColor == null ? null : licenceColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_driver.driverid
     *
     * @return the value of vehicle_driver.driverid
     *
     * @mbggenerated
     */
    public Integer getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_driver.driverid
     *
     * @param driverid the value for vehicle_driver.driverid
     *
     * @mbggenerated
     */
    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }
}