package com.hqkj.example.entity;

public class VehicleUse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_use.vehicle_use_id
     *
     * @mbggenerated
     */
    private Integer vehicleUseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_use.vehicle_use
     *
     * @mbggenerated
     */
    private String vehicleUse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_use.vehicle_use_id
     *
     * @return the value of vehicle_use.vehicle_use_id
     *
     * @mbggenerated
     */
    public Integer getVehicleUseId() {
        return vehicleUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_use.vehicle_use_id
     *
     * @param vehicleUseId the value for vehicle_use.vehicle_use_id
     *
     * @mbggenerated
     */
    public void setVehicleUseId(Integer vehicleUseId) {
        this.vehicleUseId = vehicleUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_use.vehicle_use
     *
     * @return the value of vehicle_use.vehicle_use
     *
     * @mbggenerated
     */
    public String getVehicleUse() {
        return vehicleUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_use.vehicle_use
     *
     * @param vehicleUse the value for vehicle_use.vehicle_use
     *
     * @mbggenerated
     */
    public void setVehicleUse(String vehicleUse) {
        this.vehicleUse = vehicleUse == null ? null : vehicleUse.trim();
    }
}