package com.hqkj.example.entity;

public class VehicleUseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicleusetype.vcat
     *
     * @mbggenerated
     */
    private String vcat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicleusetype.vutypedesc
     *
     * @mbggenerated
     */
    private String vutypedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicleusetype.carmastertype
     *
     * @mbggenerated
     */
    private String carmastertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicleusetype.carmasterdesc
     *
     * @mbggenerated
     */
    private String carmasterdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicleusetype.vcat
     *
     * @return the value of vehicleusetype.vcat
     *
     * @mbggenerated
     */
    public String getVcat() {
        return vcat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicleusetype.vcat
     *
     * @param vcat the value for vehicleusetype.vcat
     *
     * @mbggenerated
     */
    public void setVcat(String vcat) {
        this.vcat = vcat == null ? null : vcat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicleusetype.vutypedesc
     *
     * @return the value of vehicleusetype.vutypedesc
     *
     * @mbggenerated
     */
    public String getVutypedesc() {
        return vutypedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicleusetype.vutypedesc
     *
     * @param vutypedesc the value for vehicleusetype.vutypedesc
     *
     * @mbggenerated
     */
    public void setVutypedesc(String vutypedesc) {
        this.vutypedesc = vutypedesc == null ? null : vutypedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicleusetype.carmastertype
     *
     * @return the value of vehicleusetype.carmastertype
     *
     * @mbggenerated
     */
    public String getCarmastertype() {
        return carmastertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicleusetype.carmastertype
     *
     * @param carmastertype the value for vehicleusetype.carmastertype
     *
     * @mbggenerated
     */
    public void setCarmastertype(String carmastertype) {
        this.carmastertype = carmastertype == null ? null : carmastertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicleusetype.carmasterdesc
     *
     * @return the value of vehicleusetype.carmasterdesc
     *
     * @mbggenerated
     */
    public String getCarmasterdesc() {
        return carmasterdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicleusetype.carmasterdesc
     *
     * @param carmasterdesc the value for vehicleusetype.carmasterdesc
     *
     * @mbggenerated
     */
    public void setCarmasterdesc(String carmasterdesc) {
        this.carmasterdesc = carmasterdesc == null ? null : carmasterdesc.trim();
    }
}